[dut]

ip = "thrive-dog1-usw2-api.data.plume.tech"

[userinfo]
usrid = 'thrive-android+1@plume.com'

pwd = 'plume1234'

devuserid = '6489599c9a2357000b2dc384'

sn = 'kd8c0000c6'
devid = '60B4F7B307B5'
mac = '60:B4:F7:B3:07:B5'

#sn = 'KD8F000080'
#devid = '60B4F7B30421'
#mac = '60:B4:F7:B3:04:21'


androiddev1 = 'HQ635T08E6'

Commanduuid = "00004652-08c2-11e1-9073-0e8ac72e0011"
Datauuid = "00004652-08c2-11e1-9073-0e8ac72e0013"
ResponseUUID = "00004652-08c2-11e1-9073-0e8ac72e0012"


[testapk]

pythonfile = "test-HomePass_Lanuchtest.py"

[unixtime]

adddays = 0
addhours = 1
addsecs = 30

[allurewiget]

Device = "Deity Ring"
DevVersion= "FW v0xFF.2.11"
FirmwareURL= "https://drive.google.com/file/d/1VftYP92ntZ5uynnjqGla0O9qDrT7XeXj/view?usp=sharing"

[sleep]
begin = "2022-12-12 23:00"
totalsleep = 360
[walking]
begin = "2022-12-13 10:00"
totalwalking = 90
[running]
begin = "2022-12-13 11:00"
totalrunning = 90
